/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

public class App {
    public static void main(String[] args) {
        Caneta a = new Caneta(100, "verde");
        Caneta b = new Caneta(0.02); // 50, azul
        Caneta c = new Caneta(); // 100, azul

        IO.println(a);
        IO.println(b);

    }
}
