/*
 * This source file was generated by the Gradle 'init' task
 */
package poo;

import java.util.Random;

public class App {
    static void main(String[] args) {
        Random r = new Random();
        int secreto = r.nextInt(1,101);
        int palpite = 0;
        int tentativas = 0;

        while (palpite != secreto) {
            palpite = Integer.parseInt(IO.readln("Entre com seu palpite: "));
            tentativas++;

            if (palpite < secreto) {
                IO.println("O segredo é maior");
            }
            if (palpite > secreto) {
                IO.println("O segredo é menor");
            }
        }
        IO.println("Você venceu! Número de tentativas: " + tentativas);
    }
}
