/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

import java.util.ArrayList;

public class App {


    public static void main(String[] args) {
        ArrayList<Pessoa> list = new ArrayList<>();

        list.add(new Pessoa("Bruno", "bruno@gmail.com"));
        list.add(new Pessoa("Mauricio", "mauricio@gmail.com"));
        list.add(new Pessoa("Felipe", "felipe@hotmail.com"));
        list.add(new Pessoa("Bruno", "brun33@hotmail.com"));


        list.removeIf(e -> e.getNome().equals("Bruno"));


        list.forEach(IO::println);
    }


}
