/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

public class App {
    static void main() {
        boolean invalido = true;
        String forma = "";
        int altura = 0, largura = 0;

        while (invalido) {
            forma = IO.readln("Entre com a forma desejada: \n 1 - Triângulo \n 2 - Losango \n 3 - Retângulo \n").toLowerCase();
            switch (forma) {
                case "triangulo", "triângulo", "1" -> {forma = "1"; invalido = false;
                    altura = Integer.parseInt(IO.readln("Entre com a altura do triângulo: \n"));}
                case "losango", "2" -> {forma = "2"; invalido = false;
                    altura = Integer.parseInt(IO.readln("Entre com a largura do losango: \n"));}
                case "retângulo", "retangulo", "3" -> {forma = "3"; invalido = false;
                    largura = Integer.parseInt(IO.readln("Entre com a largura do retângulo: \n"));
                    altura = Integer.parseInt(IO.readln("Entre com a altura do retângulo: \n"));}
                default -> IO.println("Entrada Inválida. Entre com o nome da forma ou número correspondente.");
            }
        }

        if (forma.equals("1")) {
            for (int i = 1; i <= altura; i++) {
                IO.println("*".repeat(i));
            }
        } else if (forma.equals("2")){
            int e1 = altura/2;
            int e2 = 1;
            for (int i = 1; i <= altura; i+=2) {
                if (e1 > 0) {
                    IO.print(" ".repeat(e1));
                    e1--;
                } else if (e1 == 0) {
                    e1++;
                }
                IO.println("*".repeat(i));

            }
            for (int i = altura-2; i > 0; i-=2) {
                IO.print(" ".repeat(e2));
                IO.println("*".repeat(i));
                e2++;
            }
        }
    }
}
