/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.oned.EAN13Writer;
import net.datafaker.Faker;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class App{
    Faker faker = new Faker();
    String teste = faker.t
    IO.println();
}

