/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Aviao a = new Aviao(5, 200, 10000, 4, "Turbina");

        a.alterarStatusGeral();

        IO.println(a);

        a.alterarStatusUnico(1);

        a.alterarStatusUnico(0);

        IO.println(a);

    }
}
