/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

public class App {
    public static void main(String[] args) {
        Ponto p1 = new Ponto(3, 4);
        Ponto p2 = new Ponto(6, 8);

        System.out.println("Ponto 1: " + p1);
        System.out.println("Ponto 2: " + p2);

        System.out.println("X do ponto 1: " + p1.getX());
        System.out.println("Y do ponto 1: " + p1.getY());

        p1.setX(5);
        p1.setY(5);

        System.out.println("Ponto 1 após alteração: " + p1);

        System.out.println("Distância: " + p1.calculaDistancia(p2));
    }
}
