/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

public class App {

    public static void main(String[] args) {
        Horario a = new Horario(2, 30, 34);
        Horario b = new Horario(1, 48);
        Horario c = new Horario(15, 0, 17);
        Horario d = new Horario(0, 57, 14);
        Horario e = new Horario(0, 16, 58);

        IO.println("a: " + a.converterSegundos());
        IO.println("b: " + b.converterSegundos());
        IO.println(a.calcularDiferenca(b));


    }
}
