/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

import java.util.HashMap;

public class App {

    private HashMap<String, Livro> Livros = new HashMap<>();
    App app = new App();

    public void main(String[] args) {
        app.cadastrar();
        app.listarIsbnTitulo();


    }

    public void cadastrar(){

        String isbn = "1234";
        String title = "Titulo";
        String author = "Autor";
        int publicationYear = 2006;

    //    String isbn = IO.readln("Entre com o ISBN do livro: ");
    //    String title = IO.readln("Entre com o título do livro: ");
    //    String author = IO.readln("Ente com o autor do livro: ");
    //    int publicationYear = Integer.parseInt(IO.readln("Entre com o ano de publicação do livro"));

        Livros.put(isbn, new Livro(isbn, title, author, publicationYear));
    }

    public void listarIsbnTitulo() {
        Livros.forEach((k, v) ->
                IO.println("ISBN: " + k + " | Título: " + v.getTitle()));
    }

    public void consultarLivroIsbn(){
        String isbn = IO.readln("Entre com o ISBN do livro: ");
        IO.println(Livros.get(isbn));
    }

    public void livrosPorAutor(){
        String author = IO.readln("Entre com o nome do autor: ");
        Livros.forEach((k, v) -> {
            if (author.equals(v.getAuthor())) {
                IO.println("ISBN: " + k + " | Título: " + v.getTitle());
            }
        });
    }
}

     //   HashMap<String, String> mapa = new HashMap<>();

     //   mapa.put("123", "Juca");
     //   mapa.put("456", "Ana");
     //   mapa.put("789", "Pedro");
     //   mapa.put("321", "Juca");
     //   String nome = mapa.get("456");
     //   mapa.forEach((chave, valor) -> IO.println("Chave: " + chave + ", Valor: " + valor));

     //   for (var elemento : mapa.entrySet()) {
     //       IO.println("Chave: " + elemento.getKey() + ", Valor: " + elemento.getValue());
     //   }

     //   mapa.values().removeIf(v -> v.equals("Juca"));
